### ISSUE TITLE
Hubot recieve messages but doesn't reply

### ISSUE THREAD

**Issue by sashich** [flowdock/hubot-flowdock#22]
Hubot recieve messages but doesn't reply

I have the following package.json:
  "dependencies": {
    "hubot-flowdock": ">=0.4.0",
    "hubot": ">= 2.4.6",
    "coffee-script": "~> 1.4.0",
    "optparse": "1.0.3",
    "scoped-http-client": "0.9.7",
    "log": "1.3.0",
    "connect": "2.3.4",
    "connect_router": "1.8.6"
  },

I've been sent messages to hubot:
@hubot, help
@hubot: help
hubot help
hubot: help
....

Hubot doesn't reply.

**Comment by ojacques** [comment]
For the records, I had the same problem. 
I had to
% npm install -g yo generator-hubot
% mkdir myhubot
% cd myhubot
% yo hubot

as per https://github.com/github/hubot/blob/master/docs/README.md

Hubot would connect, see the messages posted in the flow, but never react to them.
