### ISSUE TITLE
Flowdock adaptor broken? 

### ISSUE THREAD

**Issue by HaroldPutman** [flowdock/hubot-flowdock#74]
hubot became unresponsive when I did an npm update which picked up hubot-flowdock 0.7.5. No errors on the console, just did not respond. I rolled back to 0.7.4 and everything is happy again. 
Was there some kind of fundamental change in 0.7.5 or node-flowdock 0.9? I can't really tell from the commit logs.

```
[Wed Mar 11 2015 05:26:38 GMT-0400 (EDT)] INFO Found 2 flows.
[Wed Mar 11 2015 05:26:38 GMT-0400 (EDT)] INFO Connecting to Flowdock as user koubot (id 94314).
[Wed Mar 11 2015 05:26:38 GMT-0400 (EDT)] INFO Flowdock: connecting
[Wed Mar 11 2015 05:26:38 GMT-0400 (EDT)] INFO Flowdock: connected and streamin
```

**Comment by Mumakil** [comment]
0.7.5 update was a one line bug fix to reconnection handling and bumped node-flowdock to the latest version. Node-flowdock version bump removed official support for node 0.6. Which version were you on before?

Can you see anything relevant in the logs if you set `HUBOT_LOG_LEVEL=debug` env?

**Comment by HaroldPutman** [comment]
Not sure what was happening this morning. I tried to reproduce the issue with HUBOT_LOG_LEVEL set to debug and everything seems to work fine again. Weird.

**Comment by Mumakil** [comment]
Hi @HaroldPutman, we had someone else report similar issues, but an npm update fixed the issue. Could you tell me what npm version you're using and if updating npm and hubot-flowdock to 0.7.5 fixes the issue?

**Comment by HaroldPutman** [comment]
I am using npm version 1.4.14 and hubot-flowdock 0.7.5. I have not had any issues since reporting this 7 days agp. I am not sure what fixed it, but I think it was removing and reinstalling that did it.
